### ISSUE TITLE
Chart

### ISSUE THREAD

**Issue by jumpingmushroom** [dornquast/homeassistantwatering#1]
Hi! First off, great little project you've got going here. I'm working on something similar for my garden bed to water our fruits and vegetables. Would you mind sharing the graph config you show in the repository? I really liked the look of it :) Thanks. /Johnny

**Comment by dornquast** [comment]
Matthew, my brother, passed away unexpectedly in 2022.

-Nathan


On Apr 18, 2024, at 6:35 AM, Johnny Dalen ***@***.***> wrote:


Hi! First off, great little project you've got going here. I'm working on something similar for my garden bed to water our fruits and vegetables. Would you mind sharing the graph config you show in the repository? I really liked the look of it :) Thanks. /Johnny

**Comment by jumpingmushroom** [comment]
Oh no, I'm sorry for your loss. If it's even a moderate amount of comfort, any contributor to the home assistant and open source community will be remembered.
